version: "3.7"

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: notesapp-backend
    ports:
      - "5000:5000"
    networks:
      - app-network
  client:
    build:
      context: ./frontend
    image: notesapp-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
